basePath: /
definitions:
  model.Product:
    properties:
      category:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      price:
        type: number
      rating:
        $ref: '#/definitions/model.Rating'
      title:
        type: string
    type: object
  model.Rating:
    properties:
      count:
        type: integer
      rate:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shop API built with Go
  title: Shop API
  version: "1.0"
paths:
  /shop:
    get:
      description: Get all products from Fake Store API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
        "502":
          description: Bad Gateway
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all products
      tags:
      - Shop
swagger: "2.0"
