basePath: /
definitions:
  model.APIResponse:
    properties:
      datetime:
        type: string
      payload: {}
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shop API built with Go
  title: Shop API
  version: "1.0"
paths:
  /shop:
    get:
      description: Get all products from Fake Store API
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/model.APIResponse'
      summary: Get all products
      tags:
      - Shop
  /shop/{id}:
    get:
      description: Get a single product from Fake Store API
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.APIResponse'
      summary: Get single product
      tags:
      - Shop
swagger: "2.0"
